export const getProductsData = (categoryMap: Record<string, any>, collectionMap: Record<string, any>) => [
  {
    sku: "SC-SER-001",
    name: "Bakuchiol & Cold-Pressed Rosehip Youth Elixir",
    slug: "bakuchiol-rosehip-youth-elixir",
    brand: "Seed Cosmetics",
    category: categoryMap["serums-treatments"]._id,
    subcategory: "Facial Oil Serums",
    collectionRef: collectionMap["best-sellers"]._id,
    shortDescription: "A gentle 1% Bakuchiol night elixir suspended in organic cold-pressed rosehip seed oil. Rejuvenates texture without peeling.",
    description: "Formulated for sensitive and combination skin, this restorative night elixir combines 100% natural Bakuchiol—a gentle Ayurvedic botanical alternative to retinol—with virgin cold-pressed Rosehip Seed Oil and squalane. It actively smooths fine lines, improves cellular elasticity, and fades post-inflammatory marks without triggering dryness or photosensitivity.",
    bulletPoints: [
      "1% Pure Bakuchiol: Nature's gentle, clinical-grade alternative to synthetic retinol",
      "Cold-pressed Chilean Rosehip Seed Oil rich in natural Omega-3, 6 & 9 fatty acids",
      "Olive-derived plant Squalane for instantaneous, non-greasy lipid absorption",
      "Safe for sensitive skin and daytime wear (non-photosensitizing)",
      "Zero parabens, artificial fragrance, silicones, or mineral oil",
    ],
    benefits: [
      "Smoothes fine wrinkles and refines rough epidermal texture",
      "Restores natural skin elasticity and youthful bounce",
      "Deeply nourishes dry patches without clogging pores",
      "Calms reactive skin and reduces redness",
    ],
    ingredients: [
      { name: "Bakuchiol (1%)", keyActive: true, description: "Botanical active derived from Psoralea corylifolia seeds that stimulates collagen renewal without irritation." },
      { name: "Rosa Rubiginosa (Rosehip Seed) Oil", keyActive: true, description: "Rich in trans-retinoic acid, provitamin A, and essential fatty acids to repair skin tone." },
      { name: "Plant Squalane", keyActive: true, description: "Mimics natural skin sebum to ensure deep penetration and featherlight finish." },
      { name: "Tocopherol (Vitamin E)", keyActive: false, description: "Potent antioxidant that shields oils from rancidity and protects skin cells." },
    ],
    formulationNotes: "Cold-pressed extraction preserves sensitive bio-actives. Dermatologically tested in independent Indian clinical trials on Fitzpatrick skin phototypes III-V.",
    howToUse: "Warm 3–4 drops between clean palms and gently press onto cleansed, slightly damp face and neck as the final step in your evening routine.",
    precautions: "For external use only. Perform a 24-hour patch test inside the elbow before first use. Store in a cool, dark place away from direct sunlight.",
    faqs: [
      { question: "Can I use this if I have active acne?", answer: "Yes! Bakuchiol has natural anti-inflammatory and antibacterial properties, and rosehip oil has a comedogenic rating of 1, making it safe for acne-prone skin." },
      { question: "Can I use this during pregnancy or breastfeeding?", answer: "Unlike traditional retinoids, natural Bakuchiol is generally considered gentle and pregnancy-safe; however, always consult your physician." },
      { question: "When will I see noticeable results?", answer: "Most users notice increased morning suppleness within 7 days, and visible smoothing of texture after 4–6 weeks of consistent night use." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1000&q=80", alt: "Seed Cosmetics Bakuchiol and Rosehip Youth Elixir dropper bottle", isPrimary: true },
      { url: "https://images.unsplash.com/photo-1608248597359-59754f923297?auto=format&fit=crop&w=1000&q=80", alt: "Golden oil texture on botanical ivory background" },
    ],
    thumbnail: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80",
    hasVariants: true,
    MRP: 1199,
    sellingPrice: 899,
    discountType: "percentage",
    discountValue: 25,
    taxPercent: 18,
    stock: 45,
    lowStockThreshold: 5,
    status: "published",
    rating: 4.9,
    reviewCount: 128,
    skinType: ["All Skin Types", "Sensitive", "Dry", "Combination"],
    skinConcern: ["Anti-Aging", "Fine Lines", "Dullness", "Texture"],
    featured: true,
    bestSeller: true,
    newArrival: false,
    publishedAt: new Date(),
    seo: {
      title: "Bakuchiol & Rosehip Youth Elixir (Retinol Alternative) | Seed Cosmetics",
      metaDescription: "Gentle 1% Bakuchiol anti-aging elixir in cold-pressed rosehip seed oil. Visibly smooths lines & boosts elasticity without irritation. Order online across India.",
      canonicalUrl: "https://www.seedcosmetics.in/products/bakuchiol-rosehip-youth-elixir",
      targetTopic: "Bakuchiol natural retinol alternative serum",
      relatedTopics: ["Rosehip facial oil", "Anti-aging skincare for sensitive skin", "Ayurvedic Bakuchiol"],
    },
    variants: [
      { sku: "SC-SER-001-30ML", title: "30 ml", sizeVolume: "30ml", mrp: 1199, price: 899, stock: 30, isDefault: true },
      { sku: "SC-SER-001-50ML", title: "50 ml (Value Pack)", sizeVolume: "50ml", mrp: 1799, price: 1299, stock: 15, isDefault: false },
    ],
  },
  {
    sku: "SC-TON-002",
    name: "Niacinamide 5% & Green Tea Pore Refining Clarifying Mist",
    slug: "niacinamide-green-tea-clarifying-mist",
    brand: "Seed Cosmetics",
    category: categoryMap["toners-mists"]._id,
    subcategory: "Clarifying Toners",
    collectionRef: collectionMap["best-sellers"]._id,
    shortDescription: "A soothing, alcohol-free clarifying facial mist that refines enlarged pores, regulates excess sebum, and strengthens the skin barrier.",
    description: "Infused with pure Nilgiri green tea hydrosol, 5% clinical-grade Niacinamide, and Centella Asiatica, this ultra-fine mist delivers immediate hydration while refining enlarged pores. Perfect for Indian climates, it keeps skin fresh, matte, and balanced throughout the day.",
    bulletPoints: [
      "5% Clinical Niacinamide (Vitamin B3) to tighten pores and even out skin tone",
      "Steam-distilled organic Nilgiri Green Tea hydrosol rich in EGCG polyphenols",
      "Alcohol-free and non-drying formulation",
      "Micro-fine mist pump for even, refreshing cloud application",
      "Calms post-sun redness and controls midday shine",
    ],
    benefits: [
      "Minimizes the look of enlarged pores",
      "Balances midday oiliness without stripping essential moisture",
      "Soothes inflamed or acne-prone skin",
      "Primes skin for maximum serum absorption",
    ],
    ingredients: [
      { name: "Camellia Sinensis (Green Tea) Leaf Water", keyActive: true, description: "Potent botanical antioxidant that soothes irritation and protects against oxidative stress." },
      { name: "Niacinamide (5%)", keyActive: true, description: "Restores barrier lipids and reduces sebum hyper-secretion." },
      { name: "Centella Asiatica (Cica) Extract", keyActive: true, description: "Ancient restorative herb that accelerates epidermal repair." },
      { name: "Sodium Hyaluronate", keyActive: false, description: "Low molecular weight hyaluronic acid for multi-depth hydration." },
    ],
    formulationNotes: "Formulated at physiological skin pH 5.2. Non-sticky, fast-absorbing water texture.",
    howToUse: "Hold mist bottle 8–10 inches away and spritz 3–4 times over face with eyes closed. Use post-cleansing or anytime your skin needs a reviving hydration boost.",
    precautions: "Avoid spraying directly into open eyes. In case of contact, rinse thoroughly with cool water.",
    faqs: [
      { question: "Can I use this toner over makeup?", answer: "Absolutely. The ultra-fine micro-mist sets makeup with a natural, non-greasy satin finish and provides a quick moisture boost." },
      { question: "Is this suitable for fungal acne?", answer: "Yes, this formula contains no fatty acids or oils that trigger Malassezia folliculitis." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=80", alt: "Seed Cosmetics Niacinamide and Green Tea Mist bottle", isPrimary: true },
    ],
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80",
    hasVariants: false,
    MRP: 699,
    sellingPrice: 549,
    discountType: "percentage",
    discountValue: 21,
    taxPercent: 18,
    stock: 60,
    lowStockThreshold: 10,
    status: "published",
    rating: 4.8,
    reviewCount: 94,
    skinType: ["Oily", "Combination", "Acne-Prone", "Normal"],
    skinConcern: ["Pores", "Excess Oil", "Redness", "Uneven Tone"],
    featured: true,
    bestSeller: true,
    newArrival: false,
    publishedAt: new Date(),
    seo: {
      title: "Niacinamide 5% & Green Tea Clarifying Toner Mist | Seed Cosmetics",
      metaDescription: "Alcohol-free pore refining toner mist with 5% Niacinamide and organic Nilgiri green tea. Balances sebum and calms acne-prone skin. Buy online.",
      canonicalUrl: "https://www.seedcosmetics.in/products/niacinamide-green-tea-clarifying-mist",
      targetTopic: "Niacinamide green tea toner for pores and oily skin",
    },
  },
  {
    sku: "SC-CRM-003",
    name: "Centella & 5-Ceramide Barrier Defense Cream",
    slug: "centella-5-ceramide-barrier-cream",
    brand: "Seed Cosmetics",
    category: categoryMap["face-care"]._id,
    subcategory: "Moisturizers",
    collectionRef: collectionMap["barrier-repair"]._id,
    shortDescription: "A comforting lipid-repair moisturizer enriched with 5 skin-identical ceramides, Gotu Kola (Centella), and soothing Colloidal Oat.",
    description: "Our crown jewel for barrier repair. Formulated with a biomimetic 3:1:1:1 physiological ratio of Ceramides (EOP, NS, NP, AS, AP), Cholesterol, and Free Fatty Acids, alongside soothing Cica and Indian Oat lipids. Rescues stressed, compromised, or sensitized skin barriers overnight.",
    bulletPoints: [
      "Complex of 5 Essential Ceramides (NP, NS, AP, EOP, AS) matching skin's lipid matrix",
      "Clinical Centella Asiatica & Madecassoside to relieve burning and irritation",
      "Colloidal Oat Extract to seal moisture and prevent trans-epidermal water loss (TEWL)",
      "Rich yet non-pore-clogging cloud cream texture",
      "Fragrance-free, dye-free, essential oil-free for ultra-sensitive skin",
    ],
    benefits: [
      "Rebuilds damaged barrier within 48 hours of use",
      "Locks in deep hydration for up to 72 hours",
      "Instantly eliminates tightness, redness, and peeling",
      "Shields skin against pollution and weather fluctuations",
    ],
    ingredients: [
      { name: "Ceramide Complex (NP, NS, AP, EOP, AS)", keyActive: true, description: "Skin-identical lipid structural building blocks." },
      { name: "Centella Asiatica (Gotu Kola) Extract", keyActive: true, description: "Potent triterpenoid active that speeds up wound healing and collagen synthesis." },
      { name: "Colloidal Oatmeal", keyActive: true, description: "FDA-recognized skin protectant that relieves itchiness and inflammation." },
      { name: "Cholesterol & Fatty Acids", keyActive: false, description: "Essential lipid counterparts that enable ceramides to organize into lamellar sheets." },
    ],
    formulationNotes: "Formulated without artificial fragrance, essential oils, drying alcohols, or parabens. Non-comedogenic.",
    howToUse: "Apply a nickel-sized amount evenly over face and neck morning and evening after serums. Gently massage until fully absorbed.",
    precautions: "For external use only. If irritation occurs, discontinue use and consult a dermatologist.",
    faqs: [
      { question: "Is this moisturizer too heavy for humid weather?", answer: "Not at all. The formulation utilizes a breathable liquid-crystal emulsion that absorbs thoroughly without leaving a sticky or greasy residue." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=80", alt: "Ceramide cream jar on natural textured marble", isPrimary: true },
    ],
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80",
    hasVariants: true,
    MRP: 999,
    sellingPrice: 749,
    discountType: "percentage",
    discountValue: 25,
    taxPercent: 18,
    stock: 50,
    lowStockThreshold: 5,
    status: "published",
    rating: 4.9,
    reviewCount: 156,
    skinType: ["All Skin Types", "Dry", "Sensitive", "Compromised Barrier"],
    skinConcern: ["Barrier Repair", "Dryness", "Redness", "Flaking"],
    featured: true,
    bestSeller: true,
    newArrival: false,
    publishedAt: new Date(),
    seo: {
      title: "Centella & 5-Ceramide Barrier Defense Cream | Seed Cosmetics",
      metaDescription: "Deep barrier repair cream with 5 essential ceramides and Cica. Calms irritation, heals dryness, and locks in moisture. Safe for sensitive skin.",
      canonicalUrl: "https://www.seedcosmetics.in/products/centella-5-ceramide-barrier-cream",
      targetTopic: "Ceramide cream for damaged skin barrier India",
    },
    variants: [
      { sku: "SC-CRM-003-50G", title: "50 g", sizeVolume: "50g", mrp: 999, price: 749, stock: 35, isDefault: true },
      { sku: "SC-CRM-003-100G", title: "100 g (Family Size)", sizeVolume: "100g", mrp: 1599, price: 1199, stock: 15, isDefault: false },
    ],
  },
  {
    sku: "SC-OIL-004",
    name: "Rosemary, Bhringraj & Castor Scalp Revitalizing Oil",
    slug: "rosemary-bhringraj-scalp-oil",
    brand: "Seed Cosmetics",
    category: categoryMap["hair-care"]._id,
    subcategory: "Scalp Treatments",
    collectionRef: collectionMap["best-sellers"]._id,
    shortDescription: "Cold-pressed hair growth elixir featuring rosemary leaf extract, authentic Ayurvedic Bhringraj, and Jamaican Black Castor oil.",
    description: "Rooted in clinical hair science and traditional Ayurvedic wisdom, this targeted scalp oil stimulates follicular microcirculation, decreases seasonal hair shedding, and provides deep root nutrition.",
    bulletPoints: [
      "High-carnosic acid Rosemary Leaf Extract to stimulate dormant follicles",
      "Traditional Bhringraj (Eclipta Alba) infused in cold-pressed virgin Sesame Oil",
      "Cold-pressed Castor seed oil to thicken the hair shaft and nourish scalp",
      "Includes precision root applicator for direct scalp delivery",
      "Zero mineral oil, artificial colorants, or silicone build-up",
    ],
    benefits: [
      "Noticeably reduces hair fall within 6 to 8 weeks",
      "Revitalizes thinning edges and boosts root density",
      "Calms itchy, flaky scalp conditions",
      "Promotes thicker, shinier hair growth",
    ],
    ingredients: [
      { name: "Rosmarinus Officinalis (Rosemary) Extract", keyActive: true, description: "Proven botanical that improves blood circulation around hair follicles." },
      { name: "Eclipta Prostrata (Bhringraj) Extract", keyActive: true, description: "Known in Ayurveda as the King of Hair for maintaining pigment and follicle strength." },
      { name: "Ricinus Communis (Castor) Seed Oil", keyActive: true, description: "High in ricinoleic acid to seal moisture into brittle hair strands." },
    ],
    formulationNotes: "Made using traditional Kshirpak method infused with modern steam-distilled rosemary actives.",
    howToUse: "Part dry hair and apply 2–3 dropperfuls directly to the scalp. Gently massage with fingertips for 5 minutes. Leave on for at least 1 hour or overnight before washing.",
    precautions: "Avoid contact with eyes. Do not use on broken or infected scalp.",
    faqs: [
      { question: "How often should I oil my scalp?", answer: "We recommend using this revitalizing oil 2 to 3 times a week for optimal follicle stimulation." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=80", alt: "Seed Cosmetics Rosemary and Bhringraj Scalp Oil", isPrimary: true },
    ],
    thumbnail: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=500&q=80",
    hasVariants: true,
    MRP: 899,
    sellingPrice: 699,
    discountType: "percentage",
    discountValue: 22,
    taxPercent: 18,
    stock: 40,
    lowStockThreshold: 5,
    status: "published",
    rating: 4.8,
    reviewCount: 112,
    skinType: ["All Hair Types", "Dry Scalp", "Thinning Hair"],
    skinConcern: ["Hair Fall", "Thinning", "Flaky Scalp", "Dryness"],
    featured: true,
    bestSeller: true,
    newArrival: false,
    publishedAt: new Date(),
    seo: {
      title: "Rosemary, Bhringraj & Castor Scalp Hair Growth Oil | Seed Cosmetics",
      metaDescription: "Pure Rosemary and Ayurvedic Bhringraj scalp oil for hair fall reduction and root strengthening. Cold-pressed botanical formula. Order online.",
      canonicalUrl: "https://www.seedcosmetics.in/products/rosemary-bhringraj-scalp-oil",
      targetTopic: "Rosemary oil for hair growth India",
    },
    variants: [
      { sku: "SC-OIL-004-100ML", title: "100 ml", sizeVolume: "100ml", mrp: 899, price: 699, stock: 25, isDefault: true },
      { sku: "SC-OIL-004-200ML", title: "200 ml (Value Size)", sizeVolume: "200ml", mrp: 1499, price: 1099, stock: 15, isDefault: false },
    ],
  },
  {
    sku: "SC-SER-005",
    name: "Kakadu Plum & 10% Vitamin C Radiance Booster",
    slug: "kakadu-plum-vitamin-c-serum",
    brand: "Seed Cosmetics",
    category: categoryMap["serums-treatments"]._id,
    subcategory: "Brightening Serums",
    collectionRef: collectionMap["best-sellers"]._id,
    shortDescription: "A gentle yet potent antioxidant serum combining wild Australian Kakadu Plum with 10% stabilized Ethyl Ascorbic Acid and Ferulic Acid.",
    description: "Experience genuine skin luminosity without the stinging sensation of traditional L-ascorbic acid. Powered by wild-harvested Kakadu Plum (the world's richest plant source of Vitamin C) and 10% ultra-stable Ethyl Ascorbic Acid, this golden serum fades sun spots and promotes a radiant complexion.",
    bulletPoints: [
      "10% Stabilized Ethyl Ascorbic Acid: Highly stable, non-oxidizing Vitamin C",
      "Wild Kakadu Plum extract containing 100x more Vitamin C than oranges",
      "0.5% Ferulic Acid for antioxidant defense against environmental smog",
      "Weightless, rapid-absorbing formula that leaves zero sticky residue",
    ],
    benefits: [
      "Brightens dull complexion and restores natural glow",
      "Fades stubborn post-acne dark spots and UV pigmentation",
      "Protects against daily pollution and free radical damage",
    ],
    ingredients: [
      { name: "3-O-Ethyl Ascorbic Acid (10%)", keyActive: true, description: "Next-generation stable Vitamin C derivative with superior dermal penetration." },
      { name: "Terminalia Ferdinandiana (Kakadu Plum) Fruit Extract", keyActive: true, description: "Superfruit packed with natural polyphenols and vitamin C." },
      { name: "Ferulic Acid (0.5%)", keyActive: true, description: "Plant-derived antioxidant that doubles the photoprotective efficiency of vitamins C and E." },
    ],
    formulationNotes: "Stabilized against oxidation. Light amber bottle protects formula from UV rays.",
    howToUse: "Apply 4–5 drops onto clean, dry skin every morning. Follow with moisturizer and broad-spectrum sunscreen.",
    precautions: "Always pair with SPF 30+ sunscreen during daytime use.",
    faqs: [
      { question: "Will this serum oxidize and turn dark brown?", answer: "No. Unlike unstable L-ascorbic acid, 3-O-Ethyl Ascorbic Acid maintains stability, potency, and clarity for the full duration of its shelf life." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1000&q=80", alt: "Kakadu Plum Vitamin C bottle", isPrimary: true },
    ],
    thumbnail: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80",
    hasVariants: false,
    MRP: 999,
    sellingPrice: 799,
    discountType: "percentage",
    discountValue: 20,
    taxPercent: 18,
    stock: 35,
    lowStockThreshold: 5,
    status: "published",
    rating: 4.7,
    reviewCount: 78,
    skinType: ["All Skin Types", "Dull", "Normal", "Combination"],
    skinConcern: ["Dullness", "Dark Spots", "Hyperpigmentation", "Sun Damage"],
    featured: true,
    bestSeller: false,
    newArrival: true,
    publishedAt: new Date(),
    seo: {
      title: "Kakadu Plum & 10% Vitamin C Radiance Serum | Seed Cosmetics",
      metaDescription: "Stable 10% Vitamin C serum with wild Kakadu Plum and Ferulic acid. Fades dark spots and boosts radiance without oxidation. Buy online.",
      canonicalUrl: "https://www.seedcosmetics.in/products/kakadu-plum-vitamin-c-serum",
      targetTopic: "Best Vitamin C serum for Indian skin",
    },
  },
  {
    sku: "SC-CLN-006",
    name: "Oat Milk & Shea Butter Hydrating Gentle Cleanser",
    slug: "oat-milk-shea-butter-cleanser",
    brand: "Seed Cosmetics",
    category: categoryMap["face-care"]._id,
    subcategory: "Cleansers",
    collectionRef: collectionMap["barrier-repair"]._id,
    shortDescription: "A velvety, non-foaming cream cleanser that melts impurities without disturbing the delicate protective acid mantle.",
    description: "Gentle cleansing without compromise. Infused with soothing colloidal oat milk, raw unrefined Shea Butter, and plant glycerin, this comforting cleanser removes sunscreen and pollutants while leaving skin conditioned and calm.",
    bulletPoints: [
      "100% Sulfate-Free (SLS/SLES-free) botanical surfactant system",
      "Colloidal Oat Milk to soothe dryness and tightness",
      "Raw African Shea Butter to maintain natural lipid hydration",
      "Slightly acidic pH 5.5 to support healthy skin microbiome",
    ],
    benefits: [
      "Cleanses thoroughly without causing dry, squeaky tightness",
      "Soothes irritated and redness-prone skin",
      "Preserves natural skin barrier function",
    ],
    ingredients: [
      { name: "Avena Sativa (Oat) Kernel Flour", keyActive: true, description: "Contains beta-glucans to soothe sensitivity." },
      { name: "Butyrospermum Parkii (Shea) Butter", keyActive: true, description: "Nourishing lipid emollient rich in vitamins A and E." },
    ],
    formulationNotes: "Physiological pH 5.5. Tested for eye safety (non-stinging).",
    howToUse: "Massage 1–2 pumps onto wet skin in circular motions for 60 seconds. Rinse with lukewarm water.",
    precautions: "For external facial use only.",
    faqs: [
      { question: "Can this remove sunscreen and light makeup?", answer: "Yes, its cream-lipid base dissolves water-resistant sunscreen and daily makeup effectively." },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=80", alt: "Seed Cosmetics Oat Milk Cleanser tube", isPrimary: true },
    ],
    thumbnail: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80",
    hasVariants: false,
    MRP: 599,
    sellingPrice: 499,
    discountType: "percentage",
    discountValue: 17,
    taxPercent: 18,
    stock: 55,
    lowStockThreshold: 10,
    status: "published",
    rating: 4.8,
    reviewCount: 65,
    skinType: ["Dry", "Sensitive", "Normal", "Compromised"],
    skinConcern: ["Dryness", "Barrier Repair", "Sensitivity"],
    featured: false,
    bestSeller: false,
    newArrival: true,
    publishedAt: new Date(),
    seo: {
      title: "Oat Milk & Shea Butter Gentle Hydrating Cleanser | Seed Cosmetics",
      metaDescription: "Sulfate-free non-foaming cleanser with oat milk and shea butter. Cleanses deeply without stripping sensitive skin. Shop online.",
      canonicalUrl: "https://www.seedcosmetics.in/products/oat-milk-shea-butter-cleanser",
      targetTopic: "Gentle non-foaming hydrating cleanser India",
    },
  },
];
